#!/usr/bin/env python3
import json
from pathlib import Path

names = []

def add(name, gender, origins, themes, etymology, meaning, hidden, syllables, vibe, tags=None):
    nid = "".join(c if c.isalnum() else "-" for c in name.lower().strip())
    while "--" in nid:
        nid = nid.replace("--", "-")
    nid = nid.strip("-")
    names.append({
        "id": nid,
        "name": name.strip(),
        "gender": gender,
        "origins": origins,
        "themes": themes,
        "etymology": etymology,
        "meaning": meaning,
        "hiddenMeaning": hidden,
        "syllables": syllables,
        "length": len(name.strip()),
        "vibe": vibe,
        "tags": tags or [],
    })

# === BOYS ===
add("Oliver", "boy", ["English", "French"], ["Nature", "Vintage"], "From Old French Olivier, related to Latin oliva", "Olive tree", "Peace and fruitfulness; a name that grows quietly into strength", 3, "classic")
add("James", "boy", ["English", "Hebrew", "Biblical"], ["Biblical", "Strength"], "From Hebrew Yaʿaqov via Latin Iacomus", "Supplanter", "The steady backbone of a household; classic without being cold", 1, "classic")
add("William", "boy", ["English", "German"], ["Strength", "Royalty"], "From Germanic Willhelm: will + helm", "Resolute protector", "A name that wears a crown lightly", 2, "classic")
add("Henry", "boy", ["English", "German", "French"], ["Royalty", "Strength"], "From Germanic Heimirich: home + ruler", "Ruler of the home", "Quiet authority; the king who stays close to the hearth", 2, "classic")
add("Theodore", "boy", ["Greek", "English"], ["Wisdom", "Biblical"], "From Greek Theodōros: theos + dōron", "Gift of God", "A name that feels both scholarly and warm", 3, "rising")
add("Leo", "boy", ["Latin", "English", "Italian"], ["Strength", "Short & sweet", "Royalty"], "From Latin leo", "Lion", "Courage in a compact package", 1, "classic")
add("Noah", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Nature"], "From Hebrew Noach", "Rest; comfort", "After the storm, calm waters", 1, "classic")
add("Arthur", "boy", ["Celtic", "Welsh", "English"], ["Mythology", "Royalty", "Strength"], "Possibly from Celtic artos (bear) or Roman Artorius", "Bear; noble strength", "Legend made wearable for everyday life", 2, "classic")
add("Felix", "boy", ["Latin", "German"], ["Light", "Unique"], "From Latin felix", "Happy; fortunate", "A small spark of luck in every introduction", 2, "rising")
add("Silas", "boy", ["Latin", "Greek", "Biblical"], ["Biblical", "Nature", "Vintage"], "From Latin Silvanus / Greek Silouanos", "Of the forest", "Woodland quiet with biblical roots", 2, "rising")
add("Ezra", "boy", ["Hebrew", "Biblical"], ["Biblical", "Wisdom", "Short & sweet"], "From Hebrew ʿEzra", "Help", "Scholarly and soft-spoken strength", 2, "rising")
add("Julian", "boy", ["Latin", "English", "Spanish"], ["Grace", "Vintage"], "From Latin Iulianus, of Julius", "Youthful; downy-bearded", "Roman polish with a gentle edge", 3, "classic")
add("Mateo", "boy", ["Spanish", "Hebrew"], ["Biblical", "Modern"], "Spanish form of Matthew from Hebrew Mattityahu", "Gift of God", "Warm Mediterranean light on an old blessing", 3, "rising")
add("Luca", "boy", ["Italian", "Greek"], ["Light", "Short & sweet"], "Italian form of Lucas from Greek Loukas", "From Lucania; light", "Italian ease with a bright undertone", 2, "rising")
add("Sebastian", "boy", ["Greek", "Latin", "German"], ["Grace", "Royalty"], "From Greek Sebastos, venerable", "Revered; majestic", "Long, elegant, and quietly commanding", 4, "classic")
add("Oscar", "boy", ["Irish", "Scandinavian", "English"], ["Strength", "Vintage"], "From Old Irish Oscur or Old Norse Ásgeirr", "Deer friend; god's spear", "Irish poetry meets Nordic steel", 2, "classic")
add("Finn", "boy", ["Irish", "Scandinavian"], ["Nature", "Short & sweet"], "From Irish Fionn", "Fair; white", "A breeze off the Atlantic", 1, "rising")
add("Callum", "boy", ["Scottish", "Latin"], ["Nature"], "From Latin Columba via Scottish Gaelic", "Dove", "Peace with a Highland accent", 2, "rising")
add("Rhys", "boy", ["Welsh"], ["Strength", "Short & sweet"], "From Welsh rhys", "Enthusiasm; ardor", "Compact Welsh fire", 1, "rising")
add("Owen", "boy", ["Welsh", "English"], ["Strength"], "From Welsh Owain, possibly from Eugenius", "Well-born; youthful warrior", "Solid and sunlit", 2, "classic")
add("Caleb", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Strength"], "From Hebrew Kalev", "Whole-hearted; faithful", "Loyalty that doesn't need to shout", 2, "classic")
add("Isaac", "boy", ["Hebrew", "Biblical"], ["Biblical", "Wisdom"], "From Hebrew Yitzchaq", "He will laugh", "Joy braided into an ancient name", 2, "classic")
add("Ethan", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Strength"], "From Hebrew Eitan", "Strong; enduring", "Rock-steady without being rigid", 2, "classic")
add("Samuel", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Wisdom"], "From Hebrew Shemuel", "Heard by God; name of God", "A listening kind of strength", 3, "classic")
add("Benjamin", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Grace"], "From Hebrew Binyamin", "Son of the right hand", "Favored and warm; the last becomes first", 3, "classic")
add("Daniel", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Wisdom"], "From Hebrew Daniyyel", "God is my judge", "Integrity under pressure", 3, "classic")
add("Gabriel", "boy", ["Hebrew", "Biblical", "French"], ["Biblical", "Light"], "From Hebrew Gavriʾel", "God is my strength", "Messenger energy; bright and kind", 3, "classic")
add("Michael", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Strength"], "From Hebrew Mikhaʾel", "Who is like God?", "Archangel steel wrapped in familiarity", 3, "classic")
add("Alexander", "boy", ["Greek", "English"], ["Royalty", "Strength"], "From Greek Alexandros: alexein + anēr", "Defender of men", "Epic scale, wearable every day", 4, "classic")
add("Nicholas", "boy", ["Greek", "English"], ["Light"], "From Greek Nikolaos: nikē + laos", "Victory of the people", "Generous spirit; classic cheer", 3, "classic")
add("Thomas", "boy", ["English", "Biblical"], ["Biblical", "Wisdom"], "From Aramaic Tʾoma", "Twin", "Doubt that leads to deeper faith", 2, "classic")
add("Joseph", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Wisdom"], "From Hebrew Yosef", "He will add", "Quiet increase; the dreamer's patience", 2, "classic")
add("David", "boy", ["Hebrew", "Biblical", "Welsh"], ["Biblical", "Royalty"], "From Hebrew Dawid", "Beloved", "Shepherd-king warmth", 2, "classic")
add("Adam", "boy", ["Hebrew", "Biblical"], ["Biblical", "Nature", "Short & sweet"], "From Hebrew ʾAdam", "Man; of the earth", "First light on new ground", 2, "classic")
add("Nathan", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Wisdom"], "From Hebrew Natan", "He gave", "Giftedness without showiness", 2, "classic")
add("Aaron", "boy", ["Hebrew", "Biblical"], ["Biblical", "Light"], "From Hebrew ʾAharon; meaning uncertain", "Exalted; mountain of strength", "Priestly calm beside the fire", 2, "classic")
add("Eli", "boy", ["Hebrew", "Biblical"], ["Biblical", "Short & sweet", "Light"], "From Hebrew ʿEli", "Ascended; my God", "Small name, high reach", 1, "rising")
add("Asher", "boy", ["Hebrew", "Biblical"], ["Biblical", "Light", "Nature"], "From Hebrew ʾAsher", "Happy; blessed", "Fortune that feels earned", 2, "rising")
add("Levi", "boy", ["Hebrew", "Biblical"], ["Biblical", "Short & sweet"], "From Hebrew Lewi", "Joined; attached", "Bond and belonging in three letters", 2, "rising")
add("Jude", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Short & sweet", "Vintage"], "Short form of Judah from Hebrew Yehudah", "Praised", "Literary cool with ancient roots", 1, "rising")
add("Miles", "boy", ["English", "Latin", "German"], ["Strength", "Modern"], "From Latin miles or Germanic Milo", "Soldier; merciful", "Understated grit", 1, "rising")
add("Wesley", "boy", ["English"], ["Vintage"], "From Old English west + lēah", "Western meadow", "Open fields and quiet faith", 2, "rising")
add("Brooks", "boy", ["English"], ["Nature", "Modern", "Short & sweet"], "From English surname for one near a brook", "Small stream", "Fresh water energy", 1, "rising")
add("Atlas", "boy", ["Greek"], ["Mythology", "Strength", "Unique"], "From Greek Atlas, the Titan", "To bear; to endure", "Shoulders for the sky—and for family", 2, "rising")
add("Orion", "boy", ["Greek"], ["Mythology", "Light", "Unique"], "From Greek Orion, the hunter constellation", "Rising in the sky; hunter", "Stars mapped onto a boy", 3, "rare")
add("Hugo", "boy", ["German", "French", "Spanish"], ["Wisdom", "Short & sweet"], "From Germanic hug", "Mind; spirit; heart", "Intellectual warmth with continental flair", 2, "rising")
add("Otto", "boy", ["German", "Scandinavian"], ["Vintage", "Short & sweet"], "From Old High German ot", "Wealth; fortune", "Palindrome power; vintage rebound", 2, "rising")
add("Max", "boy", ["Latin", "German", "English"], ["Strength", "Short & sweet"], "Short for Maximilian from Latin maximus", "Greatest", "Maximum personality, minimum letters", 1, "classic")
add("Louis", "boy", ["French", "German"], ["Royalty"], "From Germanic Hludwig: fame + warrior", "Famous warrior", "French court polish", 2, "classic")
add("Charles", "boy", ["French", "German", "English"], ["Royalty", "Strength"], "From Germanic Karl", "Free man", "Royal without pretension", 1, "classic")
print("boys so far", len(names))
add("George", "boy", ["Greek", "English"], ["Nature", "Royalty"], "From Greek Georgios: ge + ergon", "Farmer; earth-worker", "Grounded nobility", 1, "classic")
add("Edward", "boy", ["English"], ["Royalty", "Vintage"], "From Old English ēad + weard", "Wealthy guardian", "Steady English oak", 2, "classic")
add("Frederick", "boy", ["German", "English"], ["Royalty", "Wisdom"], "From Germanic Fridurich: peace + ruler", "Peaceful ruler", "Diplomacy crowned", 3, "classic")
add("August", "boy", ["Latin", "German", "English"], ["Royalty", "Vintage", "Nature"], "From Latin augustus", "Venerable; majestic", "Late-summer grandeur", 2, "rising")
add("Vincent", "boy", ["Latin", "French", "English"], ["Strength", "Grace"], "From Latin Vincentius from vincere", "Conquering", "Art and grit in one breath", 2, "classic")
add("Adrian", "boy", ["Latin", "English", "Spanish"], ["Grace"], "From Latin Hadrianus, of Hadria", "From Hadria; dark one", "Mediterranean dusk", 3, "classic")
add("Marcus", "boy", ["Latin", "English"], ["Strength"], "From Latin Marcus, related to Mars", "Dedicated to Mars", "Roman discipline, modern ease", 2, "classic")
add("Roman", "boy", ["Latin", "English", "Slavic"], ["Strength", "Modern"], "From Latin Romanus", "Citizen of Rome", "Empire energy, softened", 2, "rising")
add("Cassian", "boy", ["Latin"], ["Unique", "Grace"], "From Latin Cassianus", "Hollow; empty of vanity", "Monastic calm with edge", 3, "rare")
add("Cyrus", "boy", ["Greek", "English"], ["Royalty", "Strength", "Unique"], "From Old Persian Kūrush", "Sun; throne", "Ancient kingship reframed", 2, "rising")
add("Jasper", "boy", ["English", "French"], ["Nature", "Vintage"], "From Persian via French Gaspard", "Treasurer; spotted stone", "Gemstone warmth", 2, "rising")
add("Tobias", "boy", ["Hebrew", "Greek", "Biblical"], ["Biblical", "Grace"], "From Hebrew Toviyyah", "God is good", "Gentle goodness with European flair", 3, "rising")
add("Simon", "boy", ["Hebrew", "Biblical", "English"], ["Biblical", "Wisdom"], "From Hebrew Shimʿon", "He has heard", "Listening made into a name", 2, "classic")
add("Patrick", "boy", ["Latin", "Irish", "English"], ["Strength"], "From Latin Patricius", "Nobleman", "Irish saint's steadfastness", 2, "classic")
add("Declan", "boy", ["Irish"], ["Strength"], "From Irish Declán", "Full of goodness", "Coastal Irish warmth", 2, "rising")
add("Connor", "boy", ["Irish"], ["Strength"], "From Irish Conchobhar", "Lover of hounds; high will", "Loyal fire", 2, "classic")
add("Liam", "boy", ["Irish", "English"], ["Short & sweet", "Strength"], "Short form of Irish Uilliam (William)", "Resolute protector", "Irish William, distilled", 1, "classic")
add("Sean", "boy", ["Irish"], ["Short & sweet"], "Irish form of John from Hebrew Yochanan", "God is gracious", "Simple Irish grace", 1, "classic")
add("Aidan", "boy", ["Irish"], ["Light"], "From Irish Aodhán, little fire", "Little fire", "A spark that lasts", 2, "classic")
add("Brennan", "boy", ["Irish"], ["Strength"], "From Irish Ó Braonáin", "Sorrow; moisture; descendant of Braonán", "Rain-softened resolve", 2, "rising")
add("Ewan", "boy", ["Scottish"], ["Nature"], "Scottish form of Eugene / Eòghann", "Born of the yew; well-born", "Highland green", 2, "rising")
add("Hamish", "boy", ["Scottish"], ["Unique"], "Scottish form of James", "Supplanter", "James in a kilt", 2, "rare")
add("Alasdair", "boy", ["Scottish", "Greek"], ["Strength"], "Scottish Gaelic form of Alexander", "Defender of men", "Alexander with mist on the hills", 3, "rare")
add("Gareth", "boy", ["Welsh"], ["Strength", "Mythology"], "From Welsh; Arthurian knight", "Gentle; modest", "Knightly courtesy", 2, "rare")
add("Dylan", "boy", ["Welsh"], ["Nature"], "From Welsh dy + llanw", "Son of the sea; great tide", "Welsh poetry and salt air", 2, "classic")
add("Gideon", "boy", ["Hebrew", "Biblical"], ["Biblical", "Strength"], "From Hebrew Gidʿon", "Hewer; feller", "Underdog courage", 3, "rising")
add("Jonah", "boy", ["Hebrew", "Biblical"], ["Biblical", "Nature"], "From Hebrew Yonah", "Dove", "Reluctant prophet; soft landing", 2, "rising")
add("Micah", "boy", ["Hebrew", "Biblical"], ["Biblical", "Wisdom", "Short & sweet"], "From Hebrew Mikhah", "Who is like Yah?", "Prophetic brevity", 2, "rising")
add("Malachi", "boy", ["Hebrew", "Biblical"], ["Biblical", "Light"], "From Hebrew Malʾakhi", "My messenger", "News that matters", 3, "rising")
add("Xavier", "boy", ["Spanish", "Arabic"], ["Unique", "Light"], "From Basque etxe berri via St. Francis Xavier", "New house", "Sharp consonants; fresh start", 3, "rising")
add("Rafael", "boy", ["Hebrew", "Spanish", "Biblical"], ["Biblical", "Grace"], "From Hebrew Refaʾel", "God has healed", "Art and healing braided", 3, "classic")
add("Diego", "boy", ["Spanish"], ["Strength"], "Possibly from Santiago / Didacus", "Supplanter; teaching", "Spanish sun and stride", 2, "rising")
add("Santiago", "boy", ["Spanish"], ["Biblical"], "Spanish for Saint James", "Saint James", "Pilgrim roads and devotion", 4, "rising")
add("Emil", "boy", ["Latin", "German", "Scandinavian"], ["Grace", "Vintage"], "From Latin Aemilius", "Rival; eager", "Northern European quiet chic", 2, "rising")
add("Lars", "boy", ["Scandinavian", "Latin"], ["Short & sweet"], "Scandinavian form of Laurence", "From Laurentum; laurel", "Nordic brevity", 1, "rising")
add("Soren", "boy", ["Scandinavian"], ["Wisdom", "Unique"], "From Danish Søren, from Severinus", "Severe; stern", "Philosopher's name with soft edges", 2, "rare")
add("Bjorn", "boy", ["Scandinavian"], ["Strength", "Nature"], "From Old Norse bjǫrn", "Bear", "Northern wild strength", 1, "rare")
add("Erik", "boy", ["Scandinavian", "German"], ["Royalty", "Strength"], "From Old Norse Eiríkr: ei + ríkr", "Ever ruler; alone ruler", "Viking clarity", 2, "classic")
add("Magnus", "boy", ["Latin", "Scandinavian"], ["Strength", "Royalty"], "From Latin magnus", "Great", "Grandeur without apology", 2, "rising")
add("Nikolai", "boy", ["Slavic", "Greek"], ["Light"], "Slavic form of Nicholas", "Victory of the people", "Eastern European elegance", 3, "rising")
add("Dmitri", "boy", ["Slavic", "Greek"], ["Strength"], "From Greek Demetrios, of Demeter", "Follower of Demeter", "Earth and empire", 2, "rare")
add("Ivan", "boy", ["Slavic", "Hebrew"], ["Strength"], "Slavic form of John", "God is gracious", "Stark Slavic grace", 2, "classic")
add("Alexei", "boy", ["Slavic", "Greek"], ["Wisdom"], "Russian form of Alexius / Alexander", "Defender; helper", "Softened Slavic scholarship", 3, "rare")
add("Kenji", "boy", ["Japanese"], ["Wisdom", "Strength"], "Japanese: ken (strong/wise) + ji (second son/govern)", "Strong and wise; second son", "Precision and quiet power", 2, "rising")
add("Hiro", "boy", ["Japanese"], ["Short & sweet", "Strength"], "Japanese: hiro (abundant/generous/wide)", "Abundant; generous", "Wide-hearted brevity", 2, "rising")
add("Ravi", "boy", ["Indian"], ["Light", "Short & sweet"], "From Sanskrit ravi", "Sun", "Daybreak in two syllables", 2, "rising")
add("Arjun", "boy", ["Indian"], ["Strength", "Mythology"], "From Sanskrit Arjuna", "Bright; white; clear", "Epic archer's clarity", 2, "rising")
add("Vikram", "boy", ["Indian"], ["Strength", "Royalty"], "From Sanskrit vikrama", "Valour; stride", "Heroic step forward", 2, "rising")
add("Omar", "boy", ["Arabic", "Hebrew"], ["Wisdom"], "From Arabic ʿUmar", "Flourishing; long-lived", "Desert longevity and wit", 2, "classic")
add("Yusuf", "boy", ["Arabic", "Hebrew", "Biblical"], ["Biblical", "Wisdom"], "Arabic form of Joseph", "He will add", "Qur'anic beauty; dreamer's grace", 2, "classic")
print("boys mid", len(names))
add("Idris", "boy", ["Arabic", "Welsh"], ["Wisdom"], "Arabic: interpreter; Welsh: ardent lord", "Studious; fiery lord", "Scholar and spark across cultures", 2, "rare")
add("Zayn", "boy", ["Arabic"], ["Grace", "Short & sweet", "Modern"], "From Arabic zayn", "Beauty; grace", "Sleek modern elegance", 1, "rising")
add("Kwame", "boy", ["African"], ["Unique"], "Akan name for Saturday-born boys", "Born on Saturday", "Day-named destiny", 2, "rare")
add("Jabari", "boy", ["African"], ["Strength"], "From Swahili jabari", "Brave; fearless", "Courage spoken aloud", 3, "rising")
add("Malik", "boy", ["Arabic", "African"], ["Royalty"], "From Arabic malik", "King", "Royalty without the parade", 2, "rising")
add("Bodhi", "boy", ["Indian", "English"], ["Wisdom", "Nature", "Modern"], "From Sanskrit bodhi", "Awakening; enlightenment", "Quiet clarity under a tree", 2, "rising")
add("Reed", "boy", ["English"], ["Nature", "Short & sweet", "Vintage"], "From Old English hreod", "Red-haired; reed plant", "Tall grass by the water", 1, "rising")
add("Forrest", "boy", ["English"], ["Nature", "Vintage"], "From Old French forest", "Of the woods", "Deep green quiet", 2, "rising")
add("Clay", "boy", ["English"], ["Nature", "Short & sweet", "Vintage"], "From Old English clǣg", "Clay; earth", "Hands-in-the-earth honesty", 1, "rising")
add("Heath", "boy", ["English"], ["Nature", "Vintage", "Short & sweet"], "From Old English hǣth", "Heathland", "Open moor and wind", 1, "rare")
add("Sterling", "boy", ["English"], ["Royalty", "Unique"], "From Old English steorra / Middle English sterling", "Little star; of high quality", "Silver-standard character", 2, "rare")
add("Quentin", "boy", ["Latin", "French"], ["Unique", "Vintage"], "From Latin Quintinus", "Fifth", "Literary cool; fifth-born energy", 2, "rare")
add("Thaddeus", "boy", ["Biblical"], ["Biblical", "Unique", "Grace"], "From Aramaic Taddai", "Heart; courageous", "Apostolic rarity", 3, "rare")
add("Benedict", "boy", ["Latin", "English"], ["Wisdom", "Vintage"], "From Latin Benedictus", "Blessed", "Monkish kindness", 3, "rare")
add("Clement", "boy", ["Latin", "French", "English"], ["Grace", "Vintage"], "From Latin Clemens", "Merciful; gentle", "Soft strength with history", 2, "rare")
add("Percival", "boy", ["French", "English", "Welsh"], ["Mythology", "Royalty", "Unique"], "From Old French Perceval; Arthurian", "Pierces the valley", "Quest-minded knight", 3, "rare")
add("Tristan", "boy", ["Celtic", "French", "Welsh"], ["Mythology", "Grace"], "From Celtic / Pictish; Tristan and Isolde", "Tumult; sorrow (folk etymology)", "Romantic legend, tempered", 2, "rising")
add("Lorenzo", "boy", ["Italian", "Latin"], ["Grace", "Royalty"], "Italian form of Laurence", "From Laurentum; crowned with laurel", "Renaissance swagger", 3, "rising")
add("Enzo", "boy", ["Italian", "German"], ["Short & sweet", "Modern"], "Short for Lorenzo / Heinz related", "Ruler of the home; laurel", "Italian zip", 2, "rising")
add("Marco", "boy", ["Italian", "Latin", "Spanish"], ["Strength"], "Italian form of Marcus", "Dedicated to Mars", "Explorer's stride", 2, "classic")
add("Paolo", "boy", ["Italian", "Latin"], ["Grace"], "Italian form of Paul from Latin Paulus", "Small; humble", "Italian humility with style", 2, "rising")
add("Andre", "boy", ["French", "Greek"], ["Strength"], "French form of Andrew from Greek Andreas", "Manly; brave", "Parisian ease", 2, "classic")
add("Remy", "boy", ["French", "Latin"], ["Short & sweet", "Grace"], "From Latin Remigius", "Oarsman", "Culinary cool and river skill", 2, "rising")
add("Pascal", "boy", ["French", "Latin"], ["Wisdom", "Unique"], "From Latin Paschalis", "Of Easter; relating to Passover", "Spring resurrection energy", 2, "rare")
add("Henri", "boy", ["French", "German"], ["Royalty"], "French form of Henry", "Ruler of the home", "Henry in a beret", 2, "rising")
add("Cole", "boy", ["English"], ["Short & sweet", "Modern"], "From Old English cola / Nicholas short form", "Charcoal; victory of the people", "Cool charcoal brevity", 1, "classic")
add("Grant", "boy", ["English", "Scottish", "French"], ["Strength", "Short & sweet"], "From Old French grand / surname", "Great; tall", "Understated largeness", 1, "classic")
add("Dean", "boy", ["English"], ["Short & sweet", "Vintage"], "From Old English denu / Latin decanus", "Valley; church official", "Valley quiet and leadership", 1, "classic")
add("Clark", "boy", ["English"], ["Vintage", "Wisdom"], "From Latin clericus via surname", "Clerk; scholar", "Quiet competence", 1, "rising")
add("Harvey", "boy", ["French", "English"], ["Vintage", "Strength"], "From Breton Haerviu: battle + worthy", "Battle worthy", "Vintage comeback kid", 2, "rising")
add("Walter", "boy", ["German", "English"], ["Vintage", "Strength"], "From Germanic Waldhar: rule + army", "Commander of the army", "Grandfather chic revived", 2, "rising")
add("Stanley", "boy", ["English"], ["Vintage", "Nature"], "From Old English stan + lēah", "Stone clearing", "Solid ground cleared for living", 2, "rare")
add("Franklin", "boy", ["English"], ["Vintage", "Wisdom"], "From Middle English frankeleyn", "Free landholder", "Self-made dignity", 2, "rare")
add("Elliot", "boy", ["English", "French", "Hebrew"], ["Wisdom", "Modern"], "From Elijah via Old French", "My God is Yahweh", "Soft biblical scholarship", 3, "rising")
add("Graham", "boy", ["Scottish", "English"], ["Vintage", "Strength"], "From Scottish surname / Old English grand + ham", "Gravelly homestead", "Steady Scottish stone", 1, "classic")
add("Nolan", "boy", ["Irish"], ["Modern", "Strength"], "From Irish Ó Nualláin", "Champion; famous", "Irish fame, understated", 2, "rising")
add("Ronan", "boy", ["Irish"], ["Nature", "Strength"], "From Irish Rónán", "Little seal", "Coastal Irish charm", 2, "rising")
add("Sullivan", "boy", ["Irish"], ["Unique", "Vintage"], "From Irish Ó Súilleabháin", "Dark-eyed; hawk-eyed", "Irish surname elegance", 3, "rising")
add("Beckett", "boy", ["English"], ["Modern", "Unique"], "From Old English beo + cot", "Bee cottage; brook", "Literary surname cool", 2, "rising")
add("Archer", "boy", ["English"], ["Strength", "Modern"], "English occupational surname", "Bowman", "Aim and intention", 2, "rising")
print("boys done", len(names))

# === GIRLS ===
add("Olivia", "girl", ["English", "Latin"], ["Nature", "Grace"], "Feminine of Oliver from Latin oliva", "Olive tree", "Peace that wears well", 4, "classic")
add("Emma", "girl", ["German", "English", "French"], ["Grace", "Short & sweet", "Vintage"], "From Germanic ermen", "Universal; whole", "Complete in four letters", 2, "classic")
add("Charlotte", "girl", ["French", "German"], ["Royalty", "Grace"], "French feminine of Charles", "Free woman", "Royal without the fuss", 3, "classic")
add("Amelia", "girl", ["German", "English", "Latin"], ["Grace", "Strength"], "From Germanic Amalia / Latin Aemilia", "Work; industrious", "Aviator spirit in soft clothes", 4, "classic")
add("Sophia", "girl", ["Greek"], ["Wisdom", "Grace"], "From Greek sophia", "Wisdom", "Philosophy made tender", 3, "classic")
add("Isabella", "girl", ["Spanish", "Italian", "Hebrew"], ["Royalty", "Grace"], "Spanish/Italian form of Elizabeth", "God is my oath", "Romance-language grandeur", 4, "classic")
add("Mia", "girl", ["Scandinavian", "Italian", "Hebrew"], ["Short & sweet", "Modern"], "Short for Maria / Scandinavian mine", "Mine; beloved; wished-for child", "Intimate and international", 1, "classic")
add("Ava", "girl", ["Latin", "German", "English"], ["Short & sweet", "Grace", "Nature"], "Possibly from Latin avis or Germanic avi", "Bird; life; desired", "Flight in three letters", 2, "classic")
add("Evelyn", "girl", ["English", "French", "German"], ["Vintage", "Grace", "Nature"], "From Norman Aveline / Old French aveline", "Desired; hazelnut", "Vintage orchard sweetness", 3, "classic")
add("Harper", "girl", ["English"], ["Modern", "Unique"], "From English occupational surname", "Harp player", "Music and frontier grit", 2, "rising")
print("girls start", len(names))
add("Eleanor", "girl", ["French", "Greek", "English"], ["Royalty", "Vintage", "Light"], "From Occitan Aliénor / possibly Greek light", "Bright one; the other Aenor", "Queens and lamp-light", 3, "classic")
add("Grace", "girl", ["Latin", "English"], ["Grace", "Biblical", "Short & sweet"], "From Latin gratia", "Favor; elegance", "Virtue name that never ages", 1, "classic")
add("Chloe", "girl", ["Greek"], ["Nature", "Light"], "From Greek khloē", "Green shoot; blooming", "Spring in a name", 2, "classic")
add("Zoe", "girl", ["Greek"], ["Light", "Short & sweet"], "From Greek zōē", "Life", "Vitality distilled", 1, "classic")
add("Lily", "girl", ["English", "Latin"], ["Nature", "Light", "Short & sweet"], "From Latin lilium / English flower", "Lily flower", "White petals and clear intention", 2, "classic")
add("Rose", "girl", ["Latin", "English", "French"], ["Nature", "Vintage", "Short & sweet"], "From Latin rosa", "Rose flower", "Thorns optional; beauty not", 1, "classic")
add("Violet", "girl", ["Latin", "English", "French"], ["Nature", "Vintage", "Grace"], "From Latin viola", "Purple flower", "Shy color, strong presence", 3, "rising")
add("Ivy", "girl", ["English"], ["Nature", "Short & sweet", "Vintage"], "From Old English ifig", "Ivy plant", "Clinging loyalty, evergreen", 2, "rising")
add("Hazel", "girl", ["English"], ["Nature", "Vintage"], "From Old English hæsel", "Hazel tree", "Nut-brown warmth", 2, "rising")
add("Willow", "girl", ["English"], ["Nature", "Grace"], "From Old English welig", "Willow tree", "Flexible strength by the water", 2, "rising")
add("Aurora", "girl", ["Latin"], ["Mythology", "Light", "Nature"], "From Latin aurora", "Dawn", "Northern lights and first light", 3, "rising")
add("Luna", "girl", ["Latin", "Spanish", "Italian"], ["Mythology", "Light", "Nature"], "From Latin luna", "Moon", "Night sky made gentle", 2, "rising")
add("Stella", "girl", ["Latin", "Italian"], ["Light", "Vintage", "Grace"], "From Latin stella", "Star", "Starlight with Italian vowels", 2, "rising")
add("Celeste", "girl", ["Latin", "French"], ["Light", "Grace"], "From Latin caelestis", "Heavenly", "Sky-blue elegance", 3, "rising")
add("Iris", "girl", ["Greek"], ["Nature", "Mythology", "Short & sweet"], "From Greek iris", "Rainbow; messenger goddess", "Color bridging earth and sky", 2, "rising")
add("Freya", "girl", ["Scandinavian"], ["Mythology", "Strength"], "From Old Norse Freyja", "Lady; noblewoman", "Love and battle in one goddess", 2, "rising")
add("Astrid", "girl", ["Scandinavian"], ["Strength", "Light"], "From Old Norse Ástríðr: ást + fríðr", "Divine strength; beautiful love", "Nordic steel and affection", 2, "rising")
add("Ingrid", "girl", ["Scandinavian"], ["Strength", "Vintage"], "From Old Norse Ingiríðr", "Ing's beauty; fair", "Frozen beauty that thaws warm", 2, "rare")
add("Sigrid", "girl", ["Scandinavian"], ["Vintage"], "From Old Norse Sigríðr: sigr + fríðr", "Beautiful victory", "Win without losing softness", 2, "rare")
add("Nora", "girl", ["Irish", "English", "Latin"], ["Short & sweet", "Vintage"], "Short for Honora / Eleanor", "Honor; light", "Compact dignity", 2, "rising")
add("Maeve", "girl", ["Irish"], ["Mythology", "Strength", "Short & sweet"], "From Irish Medb", "She who intoxicates; the cause of great joy", "Warrior queen energy", 1, "rising")
add("Saoirse", "girl", ["Irish"], ["Unique", "Strength"], "From Irish saoirse", "Freedom", "Liberation spoken in Gaelic", 2, "rare")
add("Siobhan", "girl", ["Irish"], ["Grace"], "Irish form of Joan / Jeanne", "God is gracious", "Irish Joan with music in it", 2, "rare")
add("Niamh", "girl", ["Irish"], ["Mythology", "Light"], "From Irish niamh", "Bright; radiant", "Otherworld brightness", 1, "rare")
add("Aoife", "girl", ["Irish"], ["Mythology", "Strength"], "From Irish aoibh", "Beauty; radiance", "Warrior beauty of Irish legend", 2, "rare")
add("Fiona", "girl", ["Scottish", "Irish"], ["Nature", "Grace"], "From Gaelic fionn", "Fair; white", "Highland fairness", 3, "classic")
add("Isla", "girl", ["Scottish", "Spanish"], ["Nature", "Short & sweet"], "From Scottish island / Spanish isla", "Island", "Sea-girt calm", 2, "rising")
add("Maisie", "girl", ["Scottish", "English"], ["Vintage", "Short & sweet"], "Scottish diminutive of Margaret", "Pearl", "Cheerful Scottish pearl", 2, "rising")
add("Ailsa", "girl", ["Scottish"], ["Nature", "Unique"], "From Ailsa Craig, Scottish island rock", "Elf victory; rocky isle", "Sea rock and mist", 2, "rare")
add("Gwendolyn", "girl", ["Welsh"], ["Mythology", "Grace"], "From Welsh gwen + dolen", "White ring; blessed bow", "Arthurian white-and-gold", 3, "rare")
add("Bronwyn", "girl", ["Welsh"], ["Nature", "Grace"], "From Welsh bron + gwyn", "Fair breast; white raven", "Welsh fairness", 2, "rare")
add("Carys", "girl", ["Welsh"], ["Grace", "Short & sweet"], "From Welsh caru", "Love", "Love said the Welsh way", 2, "rising")
add("Elowen", "girl", ["Celtic"], ["Nature", "Unique"], "From Cornish elowen", "Elm tree", "Cornish woodland quiet", 3, "rare")
add("Seren", "girl", ["Welsh"], ["Light", "Short & sweet"], "From Welsh seren", "Star", "Welsh night sky", 2, "rising")
add("Claire", "girl", ["French", "Latin"], ["Light", "Short & sweet"], "From Latin clarus", "Clear; bright", "Clarity without sharp edges", 1, "classic")
add("Camille", "girl", ["French", "Latin"], ["Grace"], "From Latin Camillus", "Young ceremonial attendant", "Parisian restraint", 2, "classic")
add("Elodie", "girl", ["French", "German"], ["Nature", "Grace"], "From Germanic Aliodia / French Élodie", "Foreign wealth; marsh flower", "Soft French vowels", 3, "rising")
add("Colette", "girl", ["French", "Greek"], ["Vintage", "Short & sweet"], "French diminutive of Nicole", "Victory of the people", "Literary Paris in miniature", 2, "rising")
add("Amelie", "girl", ["French", "German", "Latin"], ["Grace"], "French form of Amelia", "Work; industrious", "Whimsy with backbone", 3, "rising")
add("Juliette", "girl", ["French", "Latin"], ["Grace", "Royalty"], "French diminutive of Julia", "Youthful", "Balcony romance, tempered", 3, "classic")
add("Margot", "girl", ["French"], ["Vintage", "Short & sweet"], "French diminutive of Margaret", "Pearl", "French pearl with bite", 2, "rising")
add("Solene", "girl", ["French", "Latin"], ["Unique", "Light"], "From Latin sollemnis", "Solemn; religious", "Quiet French solemnity", 2, "rare")
add("Lucia", "girl", ["Latin", "Italian", "Spanish"], ["Light"], "From Latin lux", "Light", "Light across Romance languages", 3, "classic")
add("Sofia", "girl", ["Greek", "Spanish", "Italian"], ["Wisdom", "Grace"], "Variant of Sophia", "Wisdom", "Wisdom with a warmer spelling", 3, "classic")
add("Valentina", "girl", ["Latin", "Italian", "Spanish"], ["Strength", "Grace"], "From Latin valens", "Strong; healthy", "Valentine's courage year-round", 4, "rising")
add("Bianca", "girl", ["Italian"], ["Light", "Grace"], "From Italian bianco", "White; fair", "Italian brightness", 3, "rising")
add("Chiara", "girl", ["Italian", "Latin"], ["Light"], "Italian form of Clara", "Clear; bright", "Italian clarity", 3, "rising")
add("Giulia", "girl", ["Italian", "Latin"], ["Grace"], "Italian form of Julia", "Youthful; of the Julii", "Roman roots, Italian music", 3, "rising")
add("Elena", "girl", ["Greek", "Spanish", "Italian", "Slavic"], ["Light"], "From Greek Helenē", "Torch; shining light", "Light that travels well", 3, "classic")
add("Carmen", "girl", ["Spanish", "Latin"], ["Unique", "Strength"], "From Latin carmen / Our Lady of Mount Carmel", "Song; garden", "Opera fire and sacred garden", 2, "classic")
print("girls mid", len(names))
add("Catalina", "girl", ["Spanish", "Greek"], ["Royalty", "Grace"], "Spanish form of Catherine", "Pure", "Island and court elegance", 4, "rising")
add("Paloma", "girl", ["Spanish", "Latin"], ["Nature"], "From Latin palumba", "Dove", "Peace with Spanish warmth", 3, "rising")
add("Ines", "girl", ["Spanish", "Greek"], ["Grace", "Vintage"], "Spanish form of Agnes", "Pure; chaste; lamb", "Spanish Agnes, sharpened", 2, "rising")
add("Esperanza", "girl", ["Spanish"], ["Light", "Unique"], "From Spanish esperanza", "Hope", "Hope spoken aloud", 4, "rare")
add("Ada", "girl", ["German", "English"], ["Wisdom", "Short & sweet", "Vintage"], "From Germanic adal / short for Adelaide", "Noble", "Computing pioneer brevity", 2, "rising")
add("Greta", "girl", ["German", "Scandinavian"], ["Vintage", "Short & sweet"], "Short for Margaret", "Pearl", "Nordic-German grit", 2, "rising")
add("Heidi", "girl", ["German"], ["Nature", "Vintage"], "Short for Adelheid", "Noble kind", "Alpine meadows and grit", 2, "classic")
add("Anneliese", "girl", ["German"], ["Grace", "Vintage"], "Compound of Anna + Liese", "Grace + God is my oath", "Layered German devotion", 4, "rare")
add("Liesel", "girl", ["German"], ["Vintage", "Grace"], "German diminutive of Elizabeth", "God is my oath", "Book-thief tenderness", 2, "rare")
add("Thea", "girl", ["Greek"], ["Mythology", "Short & sweet", "Light"], "Short for Theodora / Greek thea", "Goddess; divine gift", "Divine in three letters", 1, "rising")
add("Penelope", "girl", ["Greek"], ["Mythology", "Wisdom"], "From Greek Pēnelopē", "Weaver; duck (folk)", "Faithful cleverness", 4, "rising")
add("Helena", "girl", ["Greek"], ["Light", "Royalty"], "From Greek Helenē", "Torch; shining light", "Helen without the war", 3, "classic")
add("Calliope", "girl", ["Greek"], ["Mythology", "Unique"], "From Greek Kalliope", "Beautiful voice", "Muse of epic poetry", 4, "rare")
add("Thalia", "girl", ["Greek"], ["Mythology", "Light"], "From Greek Thaleia", "To blossom; flourishing", "Comedy muse; blooming joy", 3, "rising")
add("Daphne", "girl", ["Greek"], ["Mythology", "Nature"], "From Greek daphnē", "Laurel tree", "Mythic flight into green", 2, "rising")
add("Phoebe", "girl", ["Greek"], ["Mythology", "Light"], "From Greek phoibos", "Bright; pure", "Titan brightness", 2, "rising")
add("Athena", "girl", ["Greek"], ["Mythology", "Wisdom", "Strength"], "From Greek Athēnē", "Of Athens; goddess of wisdom", "Owl-eyed strategy", 3, "rising")
add("Artemis", "girl", ["Greek"], ["Mythology", "Nature", "Strength"], "From Greek Artemis", "Goddess of the hunt and moon", "Wild moon independence", 3, "rare")
add("Hannah", "girl", ["Hebrew", "Biblical", "English"], ["Biblical", "Grace"], "From Hebrew Channah", "Favor; grace", "Prayer answered softly", 2, "classic")
add("Sarah", "girl", ["Hebrew", "Biblical"], ["Biblical", "Royalty", "Grace"], "From Hebrew Sarah", "Princess", "Matriarchal calm", 2, "classic")
add("Rebecca", "girl", ["Hebrew", "Biblical"], ["Biblical", "Grace"], "From Hebrew Rivqah", "To bind; captivating", "Well-side kindness", 3, "classic")
add("Rachel", "girl", ["Hebrew", "Biblical"], ["Biblical", "Grace", "Nature"], "From Hebrew Rachel", "Ewe", "Gentle flock loyalty", 2, "classic")
add("Leah", "girl", ["Hebrew", "Biblical"], ["Biblical", "Grace", "Short & sweet"], "From Hebrew Leʾah", "Weary; wild cow (uncertain)", "Tender perseverance", 2, "classic")
add("Miriam", "girl", ["Hebrew", "Biblical"], ["Biblical", "Wisdom", "Strength"], "From Hebrew Miryam", "Beloved; bitter; wished-for", "Prophetess by the sea", 3, "classic")
add("Esther", "girl", ["Hebrew", "Biblical"], ["Biblical", "Royalty", "Strength"], "From Persian star / Hebrew Hadassah", "Star; myrtle", "Hidden courage crowned", 2, "classic")
add("Ruth", "girl", ["Hebrew", "Biblical"], ["Biblical", "Grace", "Short & sweet", "Vintage"], "From Hebrew Rut", "Companion; friend", "Loyal gleaning love", 1, "classic")
add("Naomi", "girl", ["Hebrew", "Biblical"], ["Biblical", "Grace", "Nature"], "From Hebrew Naʿomi", "Pleasantness", "Bitterness that turns sweet again", 3, "classic")
add("Abigail", "girl", ["Hebrew", "Biblical"], ["Biblical", "Wisdom", "Grace"], "From Hebrew ʾAvigayil", "Father's joy", "Intelligent kindness", 3, "classic")
add("Deborah", "girl", ["Hebrew", "Biblical"], ["Biblical", "Wisdom", "Strength"], "From Hebrew Devorah", "Bee", "Judge and prophetess; industrious", 3, "classic")
add("Judith", "girl", ["Hebrew", "Biblical"], ["Biblical", "Strength", "Vintage"], "From Hebrew Yehudit", "Woman of Judea; praised", "Courage with a sword of wit", 2, "classic")
add("Susanna", "girl", ["Hebrew", "Biblical", "Greek"], ["Biblical", "Nature", "Grace"], "From Hebrew Shoshannah", "Lily", "Lily of testimony", 3, "classic")
add("Noa", "girl", ["Hebrew"], ["Nature", "Short & sweet", "Modern"], "From Hebrew Noʿah (feminine)", "Motion; movement", "Movement toward peace", 1, "rising")
add("Talia", "girl", ["Hebrew"], ["Nature", "Grace"], "From Hebrew Talya", "Dew of God", "Morning dew blessing", 3, "rising")
add("Yael", "girl", ["Hebrew", "Biblical"], ["Biblical", "Strength", "Short & sweet"], "From Hebrew Yaʿel", "Ibex; mountain goat", "Sure-footed courage", 1, "rising")
add("Aaliyah", "girl", ["Arabic", "Hebrew"], ["Light", "Grace"], "From Arabic ʿāliyah", "High; exalted", "Rising voice and spirit", 3, "rising")
add("Layla", "girl", ["Arabic"], ["Light", "Nature"], "From Arabic layla", "Night", "Night poetry and devotion", 2, "rising")
add("Zara", "girl", ["Arabic", "Hebrew", "Spanish"], ["Light", "Short & sweet", "Modern"], "From Arabic zahr / Hebrew zerah", "Flower; bloom; seed", "Bloom across languages", 2, "rising")
add("Amira", "girl", ["Arabic", "Hebrew"], ["Royalty", "Grace"], "From Arabic amīra", "Princess; leader", "Leadership with softness", 3, "rising")
add("Fatima", "girl", ["Arabic"], ["Wisdom", "Grace"], "From Arabic Fāṭimah", "One who abstains; captivating", "Revered daughter; quiet power", 3, "classic")
add("Samira", "girl", ["Arabic"], ["Grace", "Unique"], "From Arabic samīr", "Companion in evening talk", "Night conversation and warmth", 3, "rising")
add("Yara", "girl", ["Arabic"], ["Nature", "Short & sweet"], "Arabic small butterfly / water lady", "Butterfly; water lady", "Delicate and mythic", 2, "rising")
add("Priya", "girl", ["Indian"], ["Grace", "Short & sweet"], "From Sanskrit priya", "Beloved", "Love said simply", 2, "rising")
add("Ananya", "girl", ["Indian"], ["Unique", "Wisdom"], "From Sanskrit ananya", "Unique; matchless", "One of a kind, literally", 3, "rising")
add("Meera", "girl", ["Indian"], ["Light", "Grace"], "From Sanskrit Mira / devotee saint", "Ocean; prosperous; devotee", "Devotional song energy", 2, "rising")
add("Indira", "girl", ["Indian"], ["Royalty", "Strength"], "From Sanskrit Indīra", "Beauty; goddess Lakshmi", "Radiant prosperity", 3, "rising")
add("Kavya", "girl", ["Indian"], ["Wisdom", "Unique"], "From Sanskrit kāvya", "Poetry; poem", "Living verse", 2, "rising")
add("Aiko", "girl", ["Japanese"], ["Grace", "Short & sweet"], "Japanese: ai (love) + ko (child)", "Loved child; child of love", "Love made into a child", 2, "rising")
add("Hana", "girl", ["Japanese", "Arabic"], ["Nature", "Short & sweet"], "Japanese flower; Arabic bliss", "Flower; happiness", "Bloom and joy across tongues", 2, "rising")
add("Sakura", "girl", ["Japanese"], ["Nature"], "Japanese sakura", "Cherry blossom", "Brief beautiful spring", 3, "rising")
add("Mei", "girl", ["Chinese", "Japanese"], ["Nature", "Short & sweet"], "Chinese plum / beautiful; Japanese bud", "Beautiful; plum", "Spring plum brevity", 1, "rising")
print("girls more", len(names))
add("Amara", "girl", ["African", "Indian"], ["Grace", "Unique"], "Igbo grace / Sanskrit immortal / Latin bitter", "Grace; immortal", "Cross-continental grace", 3, "rising")
add("Zuri", "girl", ["African"], ["Grace", "Short & sweet"], "From Swahili zuri", "Beautiful", "Beauty without apology", 2, "rising")
add("Imani", "girl", ["African"], ["Wisdom"], "From Swahili imani", "Faith", "Belief made personal", 3, "rising")
add("Amina", "girl", ["Arabic", "African"], ["Grace"], "From Arabic amīn", "Trustworthy; honest", "Trust earned quietly", 3, "classic")
add("Nia", "girl", ["African", "Welsh"], ["Short & sweet", "Wisdom"], "Swahili purpose; Welsh bright", "Purpose; bright", "Purpose in three letters", 1, "rising")
add("Sanaa", "girl", ["African", "Arabic"], ["Unique", "Grace"], "Swahili art; Arabic brilliance", "Art; radiance", "Creative light", 2, "rising")
add("Anya", "girl", ["Slavic", "Indian"], ["Grace", "Short & sweet"], "Russian diminutive of Anna; Sanskrit inexhaustible", "Grace; inexhaustible", "Slavic softness", 2, "rising")
add("Mila", "girl", ["Slavic"], ["Grace", "Short & sweet", "Modern"], "From Slavic mil", "Gracious; dear", "Dear one, internationally", 2, "rising")
add("Nadia", "girl", ["Slavic", "Arabic"], ["Grace"], "From Slavic Nadezhda / Arabic dew", "Hope; delicate", "Hope that travels", 3, "classic")
add("Katya", "girl", ["Slavic", "Greek"], ["Grace"], "Russian diminutive of Ekaterina", "Pure", "Russian Catherine, intimate", 2, "rising")
add("Olga", "girl", ["Slavic", "Scandinavian"], ["Strength", "Vintage"], "From Old Norse Helga", "Holy; blessed", "Slavic steel holiness", 2, "classic")
add("Vera", "girl", ["Slavic", "Latin"], ["Wisdom", "Short & sweet", "Vintage"], "From Russian vera / Latin verus", "Faith; truth", "Truth and faith compressed", 2, "rising")
add("Irina", "girl", ["Slavic", "Greek"], ["Grace"], "From Greek eirēnē", "Peace", "Peace with Slavic vowels", 3, "rising")
add("Svetlana", "girl", ["Slavic"], ["Light", "Unique"], "From Slavic svet", "Light; world", "Radiant Slavic light", 3, "rare")
add("Clara", "girl", ["Latin", "German", "English"], ["Light", "Vintage", "Short & sweet"], "From Latin clarus", "Clear; bright", "Brightness you can hold", 2, "classic")
add("Alice", "girl", ["German", "English", "French"], ["Wisdom", "Vintage", "Grace"], "From Germanic Adalheidis via Old French", "Noble kind", "Wonderland curiosity grounded", 2, "classic")
add("Jane", "girl", ["Hebrew", "English"], ["Biblical", "Short & sweet", "Vintage"], "From Hebrew Yochanan via Jeanne", "God is gracious", "Plain elegance perfected", 1, "classic")
add("Margaret", "girl", ["Greek", "English", "French"], ["Vintage", "Royalty", "Wisdom"], "From Greek margarītēs", "Pearl", "Pearl of great price", 3, "classic")
add("Catherine", "girl", ["Greek", "English", "French"], ["Royalty", "Wisdom", "Grace"], "From Greek Aikaterinē / katharos", "Pure", "Empress purity", 3, "classic")
add("Elizabeth", "girl", ["Hebrew", "Biblical", "English"], ["Biblical", "Royalty", "Grace"], "From Hebrew Elisheva", "God is my oath", "Queens and covenants", 4, "classic")
add("Victoria", "girl", ["Latin", "English", "Spanish"], ["Royalty", "Strength"], "From Latin victoria", "Victory", "Win worn gracefully", 4, "classic")
add("Matilda", "girl", ["German", "English"], ["Strength", "Vintage"], "From Germanic Mahthildis: might + battle", "Battle-mighty", "Strong mind, soft vowels", 3, "rising")
add("Josephine", "girl", ["French", "Hebrew"], ["Vintage", "Grace"], "French feminine of Joseph", "He will add", "Empire chic with warmth", 4, "rising")
add("Beatrice", "girl", ["Latin", "Italian", "English"], ["Wisdom", "Vintage"], "From Latin Beatrix / Viatrix", "She who brings happiness; voyager", "Blessed traveler", 3, "rising")
add("Florence", "girl", ["Latin", "English", "French"], ["Nature", "Vintage"], "From Latin Florentius", "Flourishing; blooming", "Renaissance city energy", 2, "rising")
add("Cora", "girl", ["Greek", "English"], ["Short & sweet", "Vintage", "Nature"], "From Greek Korē", "Maiden; daughter", "Persephone's spring name", 2, "rising")
add("Eliza", "girl", ["Hebrew", "English"], ["Biblical", "Vintage", "Grace"], "Short for Elizabeth", "God is my oath", "Sharper Elizabeth", 3, "rising")
add("Willa", "girl", ["German", "English"], ["Vintage", "Strength", "Short & sweet"], "Feminine of William / from wil", "Resolute protection; desire", "Literary prairie strength", 2, "rising")
add("June", "girl", ["Latin", "English"], ["Nature", "Vintage", "Short & sweet"], "From Latin Iuno / month name", "Young; of Juno", "Midsummer ease", 1, "rising")
add("Ruby", "girl", ["Latin", "English"], ["Nature", "Vintage", "Short & sweet", "Light"], "From Latin ruber via gem name", "Red gemstone", "Deep red spark", 2, "rising")
add("Pearl", "girl", ["Latin", "English"], ["Nature", "Vintage", "Short & sweet"], "From Latin perla / English gem", "Pearl", "Ocean-formed quiet luxury", 1, "rising")
add("Opal", "girl", ["English"], ["Nature", "Vintage", "Unique", "Light"], "From Sanskrit upala", "Gemstone; precious stone", "Iridescent rarity", 2, "rare")
add("Esme", "girl", ["French"], ["Short & sweet", "Unique"], "From Old French esmé", "Esteemed; loved", "Compact affection", 2, "rising")
add("Imogen", "girl", ["Celtic", "English"], ["Unique", "Grace"], "Possibly from Innogen / Celtic", "Maiden; girl; innocent", "Shakespearean soft mystery", 3, "rare")
add("Cordelia", "girl", ["Celtic", "Latin", "English"], ["Mythology", "Grace"], "Possibly from Celtic / Latin cor", "Heart; daughter of the sea", "Lear's loyal heart", 4, "rare")
add("Ophelia", "girl", ["Greek"], ["Mythology", "Unique"], "From Greek ōpheleia", "Help; benefit", "Tragic beauty reclaimed", 4, "rare")
add("Rosalie", "girl", ["Latin", "French", "German"], ["Nature", "Vintage", "Grace"], "From Latin rosa + French/German forms", "Rose", "Rose with French length", 3, "rising")
add("Genevieve", "girl", ["French", "Celtic"], ["Grace", "Strength"], "Possibly from Celtic Kenowefa", "Tribe woman; white wave", "Parisian saintly steel", 3, "rising")
add("Adelaide", "girl", ["German", "English", "French"], ["Royalty", "Vintage"], "From Germanic Adalheidis", "Noble kind", "Noble and complete", 3, "rising")
add("Evangeline", "girl", ["Greek", "English", "French"], ["Light", "Biblical"], "From Greek euangelion", "Bearer of good news", "Gospel in long vowels", 4, "rising")
add("Seraphina", "girl", ["Hebrew", "Latin"], ["Biblical", "Light", "Unique"], "From Hebrew seraphim via Latin", "Fiery one; burning ones", "Angel fire tempered", 4, "rare")
add("Isadora", "girl", ["Greek"], ["Unique", "Grace"], "From Greek Isidōros feminine", "Gift of Isis", "Dance and devotion", 4, "rare")
add("Linnea", "girl", ["Scandinavian"], ["Nature", "Unique"], "From Swedish botanist Linnaeus / twinflower", "Twinflower; lime tree", "Nordic woodland bloom", 3, "rare")
add("Wren", "girl", ["English"], ["Nature", "Short & sweet", "Unique"], "From Old English wrenna", "Small songbird", "Tiny voice, large presence", 1, "rising")
add("Juniper", "girl", ["English", "Latin"], ["Nature", "Unique", "Modern"], "From Latin iuniperus", "Juniper tree", "Spice and evergreen", 3, "rising")
add("Marigold", "girl", ["English"], ["Nature", "Vintage", "Unique"], "English flower name: Mary + gold", "Golden flower", "Garden gold", 3, "rare")
add("Poppy", "girl", ["English", "Latin"], ["Nature", "Short & sweet", "Light"], "From Latin papaver via English", "Poppy flower", "Red field cheer", 2, "rising")
add("Daisy", "girl", ["English"], ["Nature", "Vintage", "Short & sweet", "Light"], "From Old English dægesege", "Day's eye", "Open to the sun", 2, "classic")
add("Magnolia", "girl", ["English", "Latin"], ["Nature", "Unique", "Vintage"], "From botanist Magnol / flower", "Magnolia flower", "Southern bloom grandeur", 4, "rare")
add("Clementine", "girl", ["Latin", "French"], ["Vintage", "Nature", "Grace"], "Feminine of Clement / fruit name", "Merciful; citrus", "Sweet mercy and orange peel", 3, "rising")
print("girls late", len(names))
add("Ottilie", "girl", ["German", "French"], ["Vintage", "Unique"], "From Germanic ot / Ottilia", "Prosperity; fortune", "Continental vintage polish", 3, "rare")
add("Theodora", "girl", ["Greek"], ["Biblical", "Royalty", "Wisdom"], "Feminine of Theodore", "Gift of God", "Empress gift", 4, "rising")
add("Leonora", "girl", ["Italian", "German", "English"], ["Royalty", "Vintage"], "Variant of Eleanor", "Light; compassion", "Opera-house elegance", 4, "rare")
add("Cosette", "girl", ["French"], ["Unique", "Vintage"], "French diminutive related to Nicolette / Hugo", "Little thing; victory of the people", "Literary tenderness", 2, "rare")
add("Fleur", "girl", ["French"], ["Nature", "Short & sweet"], "From French fleur", "Flower", "Parisian bloom", 1, "rising")
add("Soleil", "girl", ["French"], ["Light", "Unique", "Nature"], "From French soleil", "Sun", "French sunshine", 2, "rare")
add("Maren", "girl", ["Scandinavian", "Latin"], ["Nature", "Short & sweet"], "From Latin marinus / Scandinavian", "Of the sea", "Northern sea calm", 2, "rising")
add("Liv", "girl", ["Scandinavian"], ["Short & sweet", "Nature"], "From Old Norse hlíf / modern Liv", "Protection; life", "Life in three letters", 1, "rising")
add("Saga", "girl", ["Scandinavian"], ["Mythology", "Wisdom", "Short & sweet"], "From Old Norse Sága", "Seeing one; story", "Storytelling goddess", 2, "rare")
add("Tyra", "girl", ["Scandinavian"], ["Strength", "Short & sweet"], "From Old Norse Þýri / Thor related", "Thor's struggle; of Thor", "Thunder softened", 2, "rising")
add("Sable", "girl", ["English", "French"], ["Nature", "Unique", "Modern"], "From Slavic via French sable fur", "Black; soft fur", "Dark soft luxury", 2, "rare")
add("Tabitha", "girl", ["Aramaic", "Biblical", "English"], ["Biblical", "Vintage", "Grace"], "From Aramaic Tabitha / Greek Dorcas", "Gazelle", "Acts of kindness, soft-spoken", 3, "rare")
add("Priscilla", "girl", ["Latin", "Biblical"], ["Biblical", "Vintage"], "From Latin Prisca", "Ancient; venerable", "Early church hospitality", 3, "rare")
add("Lydia", "girl", ["Greek", "Biblical"], ["Biblical", "Grace"], "From Greek Lydia, of Lydia", "Woman from Lydia", "Purple-trade entrepreneur saint", 3, "classic")
add("Sylvia", "girl", ["Latin", "English"], ["Nature", "Vintage"], "From Latin silva", "Of the forest", "Woodland classical", 3, "classic")
add("Diana", "girl", ["Latin", "Roman"], ["Mythology", "Nature", "Strength"], "From Latin Diana, Roman goddess", "Divine; heavenly", "Huntress moon", 3, "classic")
add("Helena", "girl", ["Greek"], ["Light", "Royalty"], "From Greek Helenē", "Torch; shining light", "Helen without the war", 3, "classic")

# === UNISEX ===
add("River", "unisex", ["English"], ["Nature", "Modern", "Unique"], "From English river", "Flowing water", "Always moving toward something larger", 2, "rising")
add("Phoenix", "unisex", ["Greek", "English"], ["Mythology", "Light", "Unique"], "From Greek phoinix", "Deep red; mythical bird", "Rising from what came before", 2, "rare")
add("Kai", "unisex", ["Japanese", "Scandinavian"], ["Nature", "Short & sweet", "Modern"], "Hawaiian sea; Japanese shell; Frisian form of Gerard", "Sea; shell; keeper of the keys", "Ocean in a single syllable", 1, "rising")
add("Sage", "unisex", ["English", "Latin"], ["Wisdom", "Nature", "Short & sweet"], "From Latin sapiens / English herb", "Wise one; herb", "Herb-garden wisdom", 1, "rising")
add("Ash", "unisex", ["English"], ["Nature", "Short & sweet"], "From Old English æsc", "Ash tree", "Tree and ember both", 1, "rising")
add("Eden", "unisex", ["Hebrew"], ["Biblical", "Nature", "Short & sweet"], "From Hebrew ʿEden", "Delight; paradise", "Garden before the fall", 2, "rising")
add("Shiloh", "unisex", ["Hebrew", "Biblical"], ["Biblical", "Unique"], "From Hebrew Shiloh", "Tranquil; his gift", "Place of rest and promise", 2, "rising")
add("Yuki", "unisex", ["Japanese"], ["Nature", "Short & sweet"], "Japanese: snow / happiness (depending on kanji)", "Snow; happiness", "Quiet winter brightness", 2, "rising")
add("Amari", "unisex", ["African", "Arabic"], ["Unique", "Strength"], "Possibly Yoruba or Arabic amir related", "Strength; builder; prince", "Cross-cultural resonance", 3, "rising")
add("Alex", "unisex", ["Greek", "English"], ["Short & sweet", "Modern"], "Short for Alexander/Alexandra", "Defender", "Defense in casual clothes", 1, "classic")
add("Jordan", "unisex", ["Hebrew", "English"], ["Biblical", "Nature", "Modern"], "From Hebrew Yarden", "To flow down; the river Jordan", "River crossing energy", 2, "classic")
add("Taylor", "unisex", ["English"], ["Modern"], "English occupational surname", "Tailor; cutter of cloth", "Craft and fit", 2, "classic")
add("Quinn", "unisex", ["Irish"], ["Short & sweet", "Modern"], "From Irish Ó Cuinn", "Descendant of Conn; wisdom", "Irish spark", 1, "rising")
add("Rowan", "unisex", ["Irish", "Scottish", "English"], ["Nature", "Modern"], "From Irish Ruadhán / English rowan tree", "Little red one; rowan tree", "Protective mountain ash", 2, "rising")
add("Cameron", "unisex", ["Scottish"], ["Strength", "Modern"], "From Scottish Gaelic cam + sròn", "Crooked nose", "Clan strength, soft edges", 3, "classic")
add("Avery", "unisex", ["English", "French", "German"], ["Modern", "Grace"], "From Germanic Alberich / Alfred related", "Elf counsel; ruler of elves", "Counsel with a modern cut", 3, "rising")
add("Parker", "unisex", ["English"], ["Modern", "Nature"], "English occupational surname", "Park keeper", "Green space guardian", 2, "rising")
add("Riley", "unisex", ["Irish", "English"], ["Modern", "Nature"], "From Irish Ó Raghallaigh / English rye clearing", "Valiant; rye meadow", "Open field energy", 2, "rising")
add("Skylar", "unisex", ["Dutch", "English"], ["Light", "Modern", "Unique"], "From Dutch schuyler / English sky", "Scholar; sky", "Wide open above", 2, "rising")
add("Charlie", "unisex", ["English", "French", "German"], ["Short & sweet", "Modern"], "Diminutive of Charles/Charlotte", "Free person", "Friendly freedom", 2, "classic")
add("Frankie", "unisex", ["English", "Latin", "German"], ["Vintage", "Modern"], "Diminutive of Francis/Frances", "French; free one", "Vintage friendliness", 2, "rising")
add("Jamie", "unisex", ["Scottish", "English", "Hebrew"], ["Short & sweet", "Modern"], "Diminutive of James", "Supplanter", "Scottish ease", 2, "classic")
add("Morgan", "unisex", ["Welsh", "Celtic"], ["Mythology", "Modern"], "From Welsh Morcant / sea circle", "Sea-born; bright sea", "Arthurian mist and tide", 2, "classic")
add("Casey", "unisex", ["Irish"], ["Short & sweet", "Modern"], "From Irish Ó Cathasaigh", "Vigilant; watchful", "Alert kindness", 2, "classic")
add("Finley", "unisex", ["Scottish", "Irish"], ["Nature", "Modern"], "From Scottish Fionnlagh", "Fair warrior; white hero", "Fair fight energy", 2, "rising")
add("Emery", "unisex", ["German", "English"], ["Strength", "Modern"], "From Germanic Amalric", "Industrious ruler; home power", "Work and rule softened", 3, "rising")
add("Hayden", "unisex", ["English"], ["Nature", "Modern"], "From Old English heg + denu", "Hay valley", "Valley of grass", 2, "rising")
add("Reese", "unisex", ["Welsh"], ["Short & sweet", "Modern"], "From Welsh Rhys", "Ardor; enthusiasm", "Welsh fire, unisex cut", 1, "rising")
add("Blair", "unisex", ["Scottish"], ["Short & sweet", "Modern"], "From Scottish Gaelic blár", "Plain; field", "Open ground clarity", 1, "rising")
add("Drew", "unisex", ["Greek", "English", "Scottish"], ["Short & sweet", "Modern"], "Short for Andrew", "Manly; brave", "Bravery abbreviated", 1, "classic")
add("Robin", "unisex", ["English", "German"], ["Nature", "Vintage", "Short & sweet"], "Diminutive of Robert / bird name", "Bright fame; robin bird", "Songbird and knight", 2, "classic")
add("Sunny", "unisex", ["English"], ["Light", "Nature", "Modern", "Short & sweet"], "From English sunny", "Bright; cheerful", "Weather as personality", 2, "rising")
add("Kerry", "unisex", ["Irish"], ["Nature", "Modern"], "From Irish Ciarraí / county Kerry", "Descendants of Ciar; dark one", "Irish county green", 2, "rising")
add("Shawn", "unisex", ["Irish", "English"], ["Short & sweet", "Modern"], "Anglicized Sean", "God is gracious", "Gracious and approachable", 1, "classic")
add("Jing", "unisex", ["Chinese"], ["Light", "Short & sweet"], "Chinese: jīng (essence/quiet/crystal)", "Essence; quiet; crystal", "Still water clarity", 1, "rising")
add("Ari", "unisex", ["Hebrew", "Scandinavian"], ["Short & sweet", "Strength"], "Hebrew lion; short for Ariel / Aristotle", "Lion; lion of God", "Small roar", 1, "rising")
add("Noel", "unisex", ["French", "Latin"], ["Biblical", "Short & sweet"], "From French Noël / Latin natalis", "Christmas; birth", "Midwinter joy", 1, "classic")
add("Remi", "unisex", ["French", "Latin"], ["Short & sweet", "Modern"], "Variant of Remy from Latin Remigius", "Oarsman", "River skill, soft spelling", 2, "rising")
add("Sloane", "unisex", ["Irish", "English"], ["Modern", "Unique"], "From Irish sluaghadh / surname", "Raid; expedition", "Sharp modern edge", 1, "rising")
add("Tatum", "unisex", ["English"], ["Modern", "Unique"], "From Old English Tate homestead", "Cheerful; Tate's homestead", "Surname spark", 2, "rising")

# Deduplicate and write
seen = set()
unique = []
for n in names:
    if n["id"] not in seen:
        seen.add(n["id"])
        unique.append(n)

out = Path("/workspace/namey/src/data/names.json")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(unique, indent=2, ensure_ascii=False) + "\n")
print("Wrote", len(unique), "names")
print("Boy:", sum(1 for n in unique if n["gender"] == "boy"))
print("Girl:", sum(1 for n in unique if n["gender"] == "girl"))
print("Unisex:", sum(1 for n in unique if n["gender"] == "unisex"))
